### ISSUE TITLE
L2VPN: Implement serilization of EVPN-VPWS

### ISSUE THREAD

**Issue by vidister** [wobcom/cosmo#3]
VPWS circuits are always point to point and attach to a (sub)interface.
The local/remote IDs are 24 bit wide. We could derive them from our unique interface IDs.
The interface encapsulation should be set to `ethernet-ccc` for encapsulation of full interfaces or `vlan-ccc` for single VLANs.

sample routing instance:

```
  VPWS_LOREM_IPSUM:
    description: "EVPN-VPWS: lorem ipsum"
    instance_type: evpn-vpws
    interfaces:
      - et-0/0/1.0
    route_distinguisher: ...
    vrf_target: ...
    protocols:
      evpn:
        interfaces:
          et-0/0/1.0:
            vpws_service_id:
              local: 1337
              remote: 2342
```
